selenium-hub:
  restart: always
  image: selenium/hub:latest
  ports:
    - "4444:4444"


selenium-chrome-1:
  restart: always
  image: selenium/node-chrome-debug
  stdin_open: true
  links:
    - selenium-hub:hub

selenium-chrome-2:
  restart: always
  image: selenium/node-chrome-debug
  stdin_open: true
  links:
    - selenium-hub:hub

selenium-firefox:
  restart: always
  image: selenium/node-firefox-debug
  links:
    - selenium-hub:hub
